/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/Breadcrumb/index.vue')['default']
    CateTree: typeof import('./components/CateTree/index.vue')['default']
    GiChart: typeof import('./components/GiChart/index.vue')['default']
    GiDot: typeof import('./components/GiDot/index.tsx')['default']
    GiFlexibleBox: typeof import('./components/GiFlexibleBox/index.vue')['default']
    GiFooter: typeof import('./components/GiFooter/index.vue')['default']
    GiIconSelector: typeof import('./components/GiIconSelector/index.vue')['default']
    GiOption: typeof import('./components/GiOption/index.vue')['default']
    GiOptionItem: typeof import('./components/GiOptionItem/index.vue')['default']
    GiSvgIcon: typeof import('./components/GiSvgIcon/index.vue')['default']
    GiTable: typeof import('./components/GiTable/index.vue')['default']
    GiTag: typeof import('./components/GiTag/index.tsx')['default']
    GiThemeBtn: typeof import('./components/GiThemeBtn/index.vue')['default']
    ParentView: typeof import('./components/ParentView/index.vue')['default']
    RightMenu: typeof import('./components/CateTree/RightMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
