// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GiContextMenu: typeof import('./components/GiContextMenu.vue')['default']
    GiDot: typeof import('./components/GiDot.vue')['default']
    GiFlexibleBox: typeof import('./components/GiFlexibleBox.vue')['default']
    GiFooter: typeof import('./components/GiFooter.vue')['default']
    GiIcon: typeof import('./components/GiIcon.vue')['default']
    GiIconSelector: typeof import('./components/GiIconSelector.vue')['default']
    GiLoading: typeof import('./components/GiLoading.vue')['default']
    GiNowTime: typeof import('./components/GiNowTime.vue')['default']
    GiOption: typeof import('./components/GiOption.vue')['default']
    GiOptionItem: typeof import('./components/GiOptionItem.vue')['default']
    GiSvgIcon: typeof import('./components/GiSvgIcon.vue')['default']
    GiTable: typeof import('./components/GiTable.vue')['default']
    GiTag: typeof import('./components/GiTag.vue')['default']
    GiTextRadio: typeof import('./components/GiTextRadio.vue')['default']
    GiTextSwitch: typeof import('./components/GiTextSwitch.vue')['default']
    GiThemeBtn: typeof import('./components/GiThemeBtn.vue')['default']
    GiTitle: typeof import('./components/GiTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
