/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GiButton: typeof import('./components/GiButton/index.vue')['default']
    GiCellAvatar: typeof import('./components/GiCell/GiCellAvatar.vue')['default']
    GiCellGender: typeof import('./components/GiCell/GiCellGender.vue')['default']
    GiCellStatus: typeof import('./components/GiCell/GiCellStatus.vue')['default']
    GiCellTags: typeof import('./components/GiCell/GiCellTags.vue')['default']
    GiCodeButton: typeof import('./components/GiCodeButton/index.vue')['default']
    GiCodeView: typeof import('./components/GiCodeView/index.vue')['default']
    GiDot: typeof import('./components/GiDot/index.tsx')['default']
    GiEditTable: typeof import('./components/GiEditTable/GiEditTable.vue')['default']
    GiFooter: typeof import('./components/GiFooter/index.vue')['default']
    GiForm: typeof import('./components/GiForm/src/GiForm.vue')['default']
    GiIconBox: typeof import('./components/GiIconBox/index.vue')['default']
    GiIconSelector: typeof import('./components/GiIconSelector/index.vue')['default']
    GiIframe: typeof import('./components/GiIframe/index.vue')['default']
    GiInputSearch: typeof import('./components/GiInputSearch/index.vue')['default']
    GiOption: typeof import('./components/GiOption/index.vue')['default']
    GiOptionItem: typeof import('./components/GiOptionItem/index.vue')['default']
    GiPageLayout: typeof import('./components/GiPageLayout/index.vue')['default']
    GiSpace: typeof import('./components/GiSpace/index.vue')['default']
    GiSvgIcon: typeof import('./components/GiSvgIcon/index.vue')['default']
    GiTable: typeof import('./components/GiTable/src/GiTable.vue')['default']
    GiTag: typeof import('./components/GiTag/index.tsx')['default']
    GiThemeBtn: typeof import('./components/GiThemeBtn/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitButton: typeof import('./components/GiPageLayout/SplitButton.vue')['default']
  }
}
